USE ROLE ACCOUNTADMIN;
USE DATABASE KYC_AML_DB;

-- Create the schema
CREATE SCHEMA IF NOT EXISTS SILVER;
USE SCHEMA SILVER;

SELECT *
FROM STG_KYC;
-- Clean KYC with parsed JSON
CREATE OR REPLACE VIEW STG_KYC AS
SELECT 
    CUSTOMER_ID,
    ENTITY_NAME,
    JURISDICTION,
    ENTITY_TYPE,
    PARSE_JSON(BENEFICIAL_OWNERS)[0]:name::STRING as PRIMARY_OWNER
FROM KYC_AML_DB.BRONZE.RAW_CUSTOMER_PROFILES;

-- Clean Transactions
USE SCHEMA SILVER;

CREATE OR REPLACE VIEW STG_TRANSACTIONS AS
SELECT 
    TX_ID,
    SENDER_ID,
    RECEIVER_ID,
    AMOUNT,
    CURRENCY,
    TO_TIMESTAMP_NTZ(TX_TIMESTAMP) as TX_TIMESTAMP
FROM KYC_AML_DB.BRONZE.RAW_TRANSACTIONS;