USE ROLE ACCOUNTADMIN;
USE DATABASE KYC_AML_DB;
USE SCHEMA GOLD;

-- 1. Clean slate for the Graph
TRUNCATE TABLE IF EXISTS NODES;
TRUNCATE TABLE IF EXISTS EDGES;

-- 2. CREATE NODES: Entities (Companies/Customers)
INSERT INTO NODES (NODE_ID, NODE_TYPE, LABEL)
SELECT 
    CUSTOMER_ID, 
    'ENTITY', 
    ENTITY_NAME 
FROM SILVER.STG_KYC;

-- 3. CREATE NODES: People (Ultimate Beneficial Owners)
-- We use DISTINCT because one person may own multiple entities
INSERT INTO NODES (NODE_ID, NODE_TYPE, LABEL)
SELECT DISTINCT 
    PRIMARY_OWNER, 
    'PERSON', 
    PRIMARY_OWNER 
FROM SILVER.STG_KYC 
WHERE PRIMARY_OWNER IS NOT NULL;

-- 4. CREATE EDGES: Ownership (Person -> Entity)
INSERT INTO EDGES (EDGE_ID, SOURCE_NODE, TARGET_NODE, RELATIONSHIP_TYPE, PROPERTIES)
SELECT 
    UUID_STRING(), 
    PRIMARY_OWNER, 
    CUSTOMER_ID, 
    'OWNS', 
    OBJECT_CONSTRUCT('share_pct', 100)
FROM SILVER.STG_KYC;

-- 5. CREATE EDGES: Transfers (Entity -> Entity)
INSERT INTO EDGES (EDGE_ID, SOURCE_NODE, TARGET_NODE, RELATIONSHIP_TYPE, PROPERTIES)
SELECT 
    TX_ID, 
    SENDER_ID, 
    RECEIVER_ID, 
    'TRANSFERRED_FUNDS', 
    OBJECT_CONSTRUCT(
        'amount', AMOUNT, 
        'currency', CURRENCY, 
        'timestamp', TX_TIMESTAMP
    )
FROM SILVER.STG_TRANSACTIONS;