USE ROLE ACCOUNTADMIN;
USE DATABASE KYC_AML_DB;
USE SCHEMA BRONZE;

-- 1. Check if the tables actually exist
SHOW TABLES LIKE 'RAW_%';

-- 2. If they don't exist, re-run the CREATE (Fast fix)
CREATE TABLE IF NOT EXISTS RAW_CUSTOMER_PROFILES (CUSTOMER_ID STRING, ENTITY_NAME STRING, JURISDICTION STRING, ENTITY_TYPE STRING, BENEFICIAL_OWNERS VARIANT);
CREATE TABLE IF NOT EXISTS RAW_TRANSACTIONS (TX_ID STRING, SENDER_ID STRING, RECEIVER_ID STRING, AMOUNT FLOAT, CURRENCY STRING, TX_TIMESTAMP TIMESTAMP_NTZ);
CREATE TABLE IF NOT EXISTS RAW_INTELLIGENCE_FEEDS (RAW_CONTENT VARIANT);

-- 3. Grant full access to your role (essential for dbt/Silver layer)
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA BRONZE TO ROLE ACCOUNTADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA BRONZE TO ROLE SYSADMIN;