USE ROLE ACCOUNTADMIN;
USE DATABASE KYC_AML_DB;
USE SCHEMA GOLD;

-- Create the schema


SELECT 
    e1.SOURCE_NODE as Entity_A,
    e2.SOURCE_NODE as Entity_B,
    e3.SOURCE_NODE as Entity_C,
    e3.TARGET_NODE as Back_To_A,
    e1.PROPERTIES:amount::FLOAT as Initial_Amount,
    e3.PROPERTIES:amount::FLOAT as Return_Amount
FROM GOLD.EDGES e1
JOIN GOLD.EDGES e2 ON e1.TARGET_NODE = e2.SOURCE_NODE
JOIN GOLD.EDGES e3 ON e2.TARGET_NODE = e3.SOURCE_NODE
WHERE e1.RELATIONSHIP_TYPE = 'TRANSFERRED_FUNDS'
  AND e2.RELATIONSHIP_TYPE = 'TRANSFERRED_FUNDS'
  AND e3.RELATIONSHIP_TYPE = 'TRANSFERRED_FUNDS'
  AND e3.TARGET_NODE = e1.SOURCE_NODE -- The Circle
  AND e1.SOURCE_NODE <> e2.SOURCE_NODE; -- Ensure it's not a self-transfer


CREATE OR REPLACE VIEW AGENT_CONTEXT_CIRCULAR_LOOPS AS
SELECT 
    e1.SOURCE_NODE as SUSPECT_ENTITY,
    e1.TARGET_NODE as INTERMEDIARY_1,
    e2.TARGET_NODE as INTERMEDIARY_2,
    e3.TARGET_NODE as FINAL_RECIPIENT,
    e1.PROPERTIES:amount::FLOAT as TOTAL_VOLUME,
    'High-risk circular transaction detected' as AI_HINT
FROM GOLD.EDGES e1
JOIN GOLD.EDGES e2 ON e1.TARGET_NODE = e2.SOURCE_NODE
JOIN GOLD.EDGES e3 ON e2.TARGET_NODE = e3.SOURCE_NODE
WHERE e1.RELATIONSHIP_TYPE = 'TRANSFERRED_FUNDS'
  AND e3.TARGET_NODE = e1.SOURCE_NODE; -- The loop


  